USE SUSEP_SES

-- PEGAR OS INPUTS (EQUITY, DESPESAS)
SELECT
	DES_ENTIS
	,NUM_PERIOD
	,NUM_QUADRO
	,COD_CMPID
	,DES_CMPTIT
	,VDR_VALOR
FROM 
	[WORK_ANALISE].[dbo].[SES_BALANCO]   
	
WHERE	1=1 
		AND DES_PERIOD = 'ANO' 
		AND NUM_PERIOD IN (2018,2019,2020,2021)
		AND COD_CMPID IN (3333,4069,6202,6314,6315,11237)
		AND NUM_PERIOD = 2021
ORDER BY 
		NUM_PERIOD, DES_ENTIS, NOM_QUADRO, NUM_ORDER

/*

SELECT TOP 10 *
FROM [SUSEP_SES].[dbo].[SES_PROVRAMOS]

select * from SUSEP_SES..SES_RAMOS where NORAMO LIKE '%Empres%' order by coramo

*/

-- PEGAR PPNG E RESERVAS PROPRIAS E RESSEGURADAS
SELECT DISTINCT
	prov.DAMESANO
	,prov.COENTI
	,grupos.NOENTI
	,prov.CORAMO
	,ramos.NORAMO
	,prov.PPNG
	,prov.PSL
	,prov.IBNR
	,prov.IBNER
	,prov.REC_SINLIQ
FROM 
	SUSEP_SES..SES_PROVRAMOS prov 
LEFT JOIN  
	SUSEP_SES..SES_RAMOS ramos
		ON prov.coramo = ramos.coramo
LEFT JOIN 
	SUSEP_SES..SES_GRUPOS_ECONOMICOS grupos
		ON grupos.COENTI = prov.COENTI AND grupos.DAMESANO = prov.DAMESANO
WHERE 1=1 
	  AND ramos.coramo IN (114,118) -- RESIDENCIAL e EMPRESARIAL  
	  AND prov.DAMESANO > 201800
	  AND RIGHT(prov.DAMESANO,2) = 12
ORDER BY
	prov.COENTI
	,prov.DAMESANO


-- PEGAR SINISTROS OCORRIDOS 
SELECT DISTINCT
	seg.DAMESANO
	,seg.COENTI
	,grupos.NOENTI
	,seg.CORAMO
	,ramos.NORAMO
	,seg.PREMIO_EMITIDO2
	,seg.SINISTRO_OCORRIDO
FROM 
	SUSEP_SES..SES_SEGUROS seg 
LEFT JOIN  
	SUSEP_SES..SES_RAMOS ramos
		ON seg.coramo = ramos.coramo
LEFT JOIN 
	SUSEP_SES..SES_GRUPOS_ECONOMICOS grupos
		ON grupos.COENTI = seg.COENTI AND grupos.DAMESANO = seg.DAMESANO
WHERE 1=1 
	  AND ramos.coramo IN (114,118) -- RESIDENCIAL e EMPRESARIAL  
	  AND seg.DAMESANO > 201800
