
	USE WORK_ALISSON
	GO

	DECLARE @NOMEJOB VARCHAR(100)	=	'TEMP_CARGA_SES_CSV'
  	DECLARE @SERVIDOR VARCHAR(100)	=	'SQL33\ATUARIAL2'  
	DECLARE @BANCO	VARCHAR(100)	=	'WORK_ALISSON'
	DECLARE @COMANDO1 VARCHAR(MAX) = 
	CHAR(10)+'BULK INSERT SES_SUSEP_SES_VGBL_RESGATES '+
	CHAR(10)+'FROM "\\rootbrasil.intranet\fileserver\DIRAT\USUARIOS\ALISSON\SES_SUSEP\UNZIP\Ses_vgbl_resgates.csv" '+
	CHAR(10)+'WITH (FIRSTROW = 2, FIELDTERMINATOR ='';'', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'')'

	PRINT @COMANDO1

	IF EXISTS (SELECT JOB_ID FROM MSDB.DBO.SYSJOBS_VIEW WHERE NAME = @NOMEJOB) 
	BEGIN
	EXEC MSDB.DBO.SP_DELETE_JOB @JOB_NAME=@NOMEJOB
	END
	EXEC MSDB..SP_ADD_JOB		@JOB_NAME = @NOMEJOB
	EXEC MSDB..SP_ADD_JOBSTEP	@JOB_NAME = @NOMEJOB, @STEP_NAME = 'STEP1', @STEP_ID = 1, @SUBSYSTEM = N'TSQL', @COMMAND = @COMANDO1, @DATABASE_NAME = @BANCO, @ON_SUCCESS_ACTION = 3
	EXEC MSDB..SP_ADD_JOBSERVER	@JOB_NAME = @NOMEJOB, @SERVER_NAME = @SERVIDOR
	EXEC MSDB..SP_START_JOB		@JOB_NAME = @NOMEJOB, @STEP_NAME = 'STEP1'
	--EXEC MSDB.DBO.SP_DELETE_JOB @JOB_NAME=@NOMEJOB